# Generated by Django 4.1.4 on 2022-12-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='modoPreparo',
            field=models.TextField(),
        ),
    ]
