# Generated by Django 4.1.4 on 2022-12-14 17:08

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('pessoas', '0001_initial'),
         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receitas', '0002_alter_receita_modopreparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            # field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pessoas.pessoa'),
            # preserve_default=False,
        ),
    ]
