# Generated by Django 4.1.4 on 2022-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0004_receita_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='fotoReceita',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
