# Generated by Django 4.1.4 on 2022-12-14 18:29

from django.db import migrations, models
import receitas.models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0005_receita_fotoreceita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='fotoReceita',
            field=models.ImageField(blank=True, upload_to=receitas.models.mudarNomeImagem),
        ),
    ]
